
            ; Custom PHP configuration for Laravel
            extension=pdo.so
            extension=pdo_mysql.so  ; Enable MySQL PDO extension
            upload_max_filesize=10M  ; Max file upload size
            post_max_size=10M  ; Max POST size
            memory_limit=128M  ; Max memory limit
            max_execution_time=300  ; Max execution time in seconds
           

        